// <auto-generated />
namespace TP1_Module_6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changemnarmes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changemnarmes));
        
        string IMigrationMetadata.Id
        {
            get { return "202003231125065_changemn armes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
